//v1

create view listeactualite as select 
ca.TYPE_CATEG_ACTU AS TYPE_CATEG_ACTU,
ca.TITRE_CATEG_ACTU AS TITRE_CATEG_ACTU,
ad0.CODE_A0 AS CODE_A0,
ad0.CAPTION_A0 AS CAPTION_A0,
ad0.COORD_X_A0 AS COORD_X_A0,
ad0.COORD_Y_A0 AS COORD_Y_A0,
ad1.CODE_A1 AS CODE_A1,
ad1.CAPTION_A1 AS CAPTION_A1,
ad1.COORD_X_A1 AS COORD_X_A1,
ad1.COORD_Y_A1 AS COORD_Y_A1,
a.TITRE_ACTUALITE AS TITRE_ACTUALITE,
a.DETAIL_ACTUALITE AS DETAIL_ACTUALITE,
a.DATE_ACTUALITE AS DATE_ACTUALITE,
a.ID_LANGUE,
a.VALEUR AS VALEUR,
ad0.ID_A0,
ca.ID_CATEG_ACTU
from actualite a 
join categorie_actualite ca on ca.ID_CATEG_ACTU = a.ID_CATEG_ACTU
 join admin_1 ad1 on ad1.ID_A1 = a.ID_A1
 join admin_0 ad0 on ad0.ID_A0 = ad1.ID_A0
 
 
 /* v2 20/04/2017 */
create view listeactualite as select 
ca.TYPE_CATEG_ACTU AS TYPE_CATEG_ACTU,
ca.TITRE_CATEG_ACTU AS TITRE_CATEG_ACTU,
ad0.CODE_A0 AS CODE_A0,
ad0.CAPTION_A0 AS CAPTION_A0,
ad0.COORD_X_A0 AS COORD_X_A0,
ad0.COORD_Y_A0 AS COORD_Y_A0,
ad1.CODE_A1 AS CODE_A1,
ad1.CAPTION_A1 AS CAPTION_A1,
ad1.COORD_X_A1 AS COORD_X_A1,
ad1.COORD_Y_A1 AS COORD_Y_A1,
a.TITRE_ACTUALITE AS TITRE_ACTUALITE,
a.DETAIL_ACTUALITE AS DETAIL_ACTUALITE,
a.DATE_ACTUALITE AS DATE_ACTUALITE,
a.ID_LANGUE,
'0' AS VALEUR,
ad0.ID_A0,
ca.ID_CATEG_ACTU,
m.CODE_MENACE,
m.TITRE_MENACE
from actualite a 
join categorie_actualite ca on ca.ID_CATEG_ACTU = a.ID_CATEG_ACTU
join menaces m on m.ID_MENACE = a.ID_MENACE
 join admin_1 ad1 on ad1.ID_A1 = a.ID_A1
 join admin_0 ad0 on ad0.ID_A0 = ad1.ID_A0